OrdererOrgs:
  - Name: Orderer
    Domain: centralbank.cbdc
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

  - Name: OrdererConsortium
    Domain: consortium.cbdc
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: OrgCentralBank
    Domain: centralbank.cbdc
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: OrgBankConsortium
    Domain: consortium.cbdc
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: OrgRegulator
    Domain: regulator.cbdc
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
