apiVersion: v2
name: cbdc-platform
description: A Helm chart for deploying the eNaira CBDC Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - cbdc
  - enaira
  - blockchain
  - hyperledger-fabric
home: https://enaira.gov.ng
maintainers:
  - name: CBN DevOps Team
    email: devops@cbn.gov.ng
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
